Repository therohit777/Hacktober_algo_bucket, pull requests merged in 2022-10, with the labels that each got.

#6 Rotate linkedklist
  Rotate_linkedlist.cpp
Labels: hacktoberfest

#9 swap nodes of a linked list in pair
  LinkedList/SwapNodesInPair.cpp
Labels: hacktoberfest-accepted

#8 balanced parentheses
  Stacks and Queues/balanced parentheses
Labels: hacktoberfest-accepted

#7 added dfs code #1
  Graph/dfs.cpp
Labels: hacktoberfest-accepted

#10 Recusive Bubble Sort added
  Recursion/recusrivebubblesort.cpp
Labels: hacktoberfest-accepted

#13 Binary Tree - Level Order Traversal
  Trees/BinaryTreeLevelOrder.cpp
Labels: hacktoberfest-accepted

#12 Added code for tower of hanoi
  Recursion/tower_of_hanoi.cpp
Labels: hacktoberfest-accepted

#11 added cycleDetection in linked list code
  Graph/bfs.cpp
  LinkedList/cycleDetection.cpp
Labels: hacktoberfest-accepted

#14 Union-Find Algorithm
  Union-Find Algorithm
Labels: hacktoberfest-accepted

#18 Create keypad_combinations.cpp
  Recursion/keypad_combinations.cpp
Labels: hacktoberfest-accepted

#15 array implementation of stacks
  .vscode/settings.json
  Stacks and Queues/array_implementation_stacks.cpp
Labels: hacktoberfest-accepted

#20 Reverse the linked list
  LinkedList/Reverse.cpp
Labels: hacktoberfest-accepted

#19 Add cpp code for fibonacci numbers
  Dynamic Programming/fibonacci.cpp
Labels: hacktoberfest-accepted

#21 added polynomials operation using linked list in c++
  LinkedList/poly_add.cpp
  LinkedList/poly_multiply.cpp
Labels: hacktoberfest-accepted

#26 Queue_using_linked_list.c
  LinkedList/Queue_using_linked_list.c
Labels: hacktoberfest-accepted

#25 topological sort added
  Graph/topologicalSort.cpp
Labels: hacktoberfest-accepted

#24 DP - Longest Palindromic Subsequence
  Dynamic Programming/LongestPalindromicSubsequence.cpp
  Dynamic Programming/LongestPalindromicSubsequence.exe
Labels: hacktoberfest-accepted

#23 Added Merge sort
  Recursion/mergesort.cpp
Labels: hacktoberfest-accepted

#17 keypad_combinations
  Recursion/keypad_combinations.cpp
Labels: hacktoberfest-accepted

#28 Remove Nth Node From End of List
  LinkedList/Remove_Nth_Node_From_End_of_List.cpp
Labels: hacktoberfest-accepted

#30 Floyd_Warshall_Algorithm.cpp
  Graph/Floyd_Warshall_Algorithm.cpp
Labels: hacktoberfest-accepted

#31 Create Circular Linked List
  LinkedList/Circular Linked List
Labels: hacktoberfest-accepted

#29 added circular linked list programs
  LinkedList/CircularLinkedList.c
  Stacks and Queues/infixtopostfix.c
Labels: hacktoberfest-accepted

#27 CircularSinglyLinkedList.cpp
  LinkedList/CircularSinglyLinkedList.cpp
Labels: hacktoberfest-accepted

#38 solved Recursion Fibonacci Series in java
  Recursion_Fibonacci_Series.java
Labels: hacktoberfest-accepted

#37 Added files for Factorial and Taylor series(Recursive program)
  Recursion/factorial.cpp
  Recursion/taylor_series.cpp
Labels: hacktoberfest-accepted

#32 Pratheeksha_hacktoberfest
  Stacks and Queues/Implementation of Queue using Linked List
Labels: hacktoberfest-accepted

#35 Add files via upload
  Recursion/selection_sort.cpp
Labels: hacktoberfest-accepted

#40 Kruskal_Algorithm.cpp
  Graph/Kruskal_Algorithm.cpp
Labels: hacktoberfest-accepted

#39 Prims_Algorithm
  Graph/Prims_Algorithm
Labels: hacktoberfest-accepted

#45 All Tree travesal in single one
  All Tree travesal in single one
Labels: hacktoberfest-accepted

#44 Subset Problem
  Recursion/Subset Problem
Labels: hacktoberfest-accepted

#43 initial commit to add files for the AVL Trees
  Trees/AVL_Tree.cpp
Labels: hacktoberfest-accepted

#42 Insertion_Sort.cpp
  Recursion/Insertion_Sort.cpp
Labels: hacktoberfest-accepted

#47 Create ArraySum.java
  Recursion/ArraySum.java
Labels: hacktoberfest-accepted

#46 commit to add program fro BST
  Trees/BST.cpp
Labels: hacktoberfest-accepted

#48 Huffman Coding using cpp
  HuffmanCoding.cpp
Labels: hacktoberfest-accepted

#49 Added Stack & Queues Program
  Stacks and Queues/Postfixvevaluation.c
  Stacks and Queues/Queue_using_stack.c
  Stacks and Queues/StringPalindromeusingstack.c
  Stacks and Queues/Towerofhanoi.c
  Stacks and Queues/balancedparentheses.cpp
Labels: hacktoberfest-accepted

#51 Add files via upload
  Graph/Kosaraju's Algo.cpp
Labels: hacktoberfest-accepted

#52 Josephus.cpp and MergesortedLL
  LinkedList/merge_Two_sorted_linkedList..java
  Recursion/Josephus.cpp
Labels: hacktoberfest-accepted

#53 Create InverseLinkedList.cpp
  InverseLinkedList.cpp
Labels: hacktoberfest-accepted

#54 Create bubble_sort.py
  bubble_sort.py
Labels: hacktoberfest-accepted

#55 Create prime_number.cpp
  prime_number.cpp
Labels: hacktoberfest-accepted

#57 added k means clustring algorithm
  k_means.py
Labels: enhancement, hacktoberfest-accepted

#56 Create Snake _game.py
  Snake _game.py
Labels: hacktoberfest-accepted

#60 Add files via upload
  sum_of_subset.cpp
Labels: hacktoberfest-accepted

#59 Arm Strong Number
  arm_strong.cpp
Labels: hacktoberfest-accepted

#66 Create Taylor Series using Recursion
  Recursion/Taylor Series using Recursion
Labels: hacktoberfest-accepted

#65 Create Recursionproblem.cpp
  Recursionproblem.cpp
Labels: hacktoberfest-accepted

#64 Create Linked list.cpp
  Linked list.cpp
Labels: hacktoberfest-accepted

#63 Bellman Ford.java
  Bellman_Ford.java
  Graph/Dijkstra's Algorithm.cpp
  Recursion/Recaman's_Sequence.cpp
Labels: hacktoberfest-accepted

#62 Dijkstra's Algorithm.cpp & Recaman's Sequence.cpp
  Graph/Dijkstra's Algorithm.cpp
  Recursion/Recaman's_Sequence.cpp
Labels: hacktoberfest-accepted

#61 Create Doubly Linked List.c
  Doubly Linked List.c
Labels: hacktoberfest-accepted

#68 Added a file named Doubly_Linked_List.cpp
  Doubly_Linked_List.cpp
Labels: hacktoberfest-accepted

#67 Biased Standings algo using cpp
  BiasedStandings.cpp
Labels: hacktoberfest-accepted

#70 Add files via upload
  linked list problem.cpp
Labels: hacktoberfest-accepted

#69 added file
  Recursion/merge_k_sorted_arrays.cpp
Labels: hacktoberfest-accepted

#75 Reverse A Number Using Recursion
  Recursion/Reverse A Number Using Recursion
Labels: hacktoberfest-accepted

#74 Create circular single linked list
  circular single linked list
Labels: hacktoberfest-accepted

#71 Dynamic Programming
  Dynamic Programming/Scramble_String.cpp
  Dynamic Programming/wildcard_matching.cpp
Labels: hacktoberfest-accepted

#72 added stack implementation using queue in C++
  Stacks and Queues/stackUsingQueue.cpp
Labels: hacktoberfest-accepted

#95 Rod Cutting Problem
  Dynamic Programming/RodCuttingProblem.cpp
Labels: hacktoberfest-accepted

#94 To Check Whether Tree is a mirror of itself.
  Trees/SymmetricTree.cpp
Labels: hacktoberfest-accepted

#93 Median of two sorted arrays
  median of two sorted array.cpp
Labels: hacktoberfest-accepted

#92 HashTable using Seperate chaining method.
  HashTableSeperateChaining.cpp
Labels: hacktoberfest-accepted

#91 Tarjan's Algorithm
  Graph/Tarjan's Algorithm
Labels: hacktoberfest-accepted

#90 Added quick sort using recursion algorithm
  Recursion/quicksort.cpp
Labels: hacktoberfest-accepted

#89 Reversing A queue Using Stack
  Stacks and Queues/Reversing A queue Using Stack
Labels: hacktoberfest-accepted

#88 NextGreaterElement.cpp
  Stacks and Queues/NextGreaterElement.cpp
Labels: hacktoberfest-accepted

#87 addKnodes.cpp
  LinkedList/addKnodes.cpp
Labels: hacktoberfest-accepted

#86 sudoku.cpp
  Recursion/sudoku.cpp
Labels: hacktoberfest-accepted

#85 largest multiple of 3(using queue).cpp
  Stacks and Queues/largest multiple of 3(using queue).cpp
Labels: hacktoberfest-accepted

#84 Reverse a String using Stack.cpp
  Stacks and Queues/Reverse a String using Stack.cpp
Labels: hacktoberfest-accepted

#83 Singly linked list is Palindrome
  LinkedList/singly linked list is Palindrome
Labels: hacktoberfest-accepted

#82 Added Heapsort using recursion
  Recursion/HeapSort.cpp
Labels: hacktoberfest-accepted

#81 Added Quicksort using recursion
  Recursion/Quicksort.cpp
Labels: hacktoberfest-accepted

#80 Added Evaluation of PostFix Expression
  Stacks and Queues/EvaluationofPostFixExpression.c
Labels: hacktoberfest-accepted

#79 Added code for search in linked list, #3
  LinkedList/SearchInLinkedList.c
Labels: hacktoberfest-accepted

#78 added code for inserting node at end of linkedlist
  LinkedList/InsertNodeAtEnd.c
Labels: hacktoberfest-accepted

#77 Path sum leetcode
  Trees/pathSum.cpp
Labels: hacktoberfest-accepted

#96 create subset_sum problem (dp)
  Dynamic Programming/subset_problem.cpp
Labels: hacktoberfest-accepted

#112 N Queens Problem Added
  .DS_Store
  Graph/GraphColringBacktracking.c
  MatrixChain.c
  NQueens Problem.c
Labels: hacktoberfest-accepted

#110 Next Permutation of ARRAY
  Recursion/Next Permutation of ARRAY
Labels: hacktoberfest-accepted

#107 Printing Subarrays of length r
  .vscode/tasks.json
  Recursion/Subarrays
  Recursion/Subarrays.cpp
Labels: hacktoberfest-accepted

#113 Merge_Two_Sorted_LL.cpp
  LinkedList/Merge_Two_Sorted_LL.cpp
Labels: hacktoberfest-accepted

#106 Open Addressing method using Quadratic Probing.
  OpenAdressingQuadraticProbing.cpp
Labels: hacktoberfest-accepted

#105 Added java code for add-two-numbers reprensented by linked List please merge it
  LinkedList/AddTwoNumbersRepresentedByLinkedList.java
Labels: hacktoberfest-accepted

#97 Added Breadth First Search algo(graphs)
  BreadthFirstSearch.cpp
Labels: hacktoberfest-accepted

#104 Create leet code question solution of linked list(206)
  leet code question solution of linked list
Labels: hacktoberfest-accepted

#101 Ternary search optimisation over binary search
  EulerianPath.cpp
  TernarySearch.cpp
Labels: hacktoberfest-accepted

#102 radixSort
  radixSort.cpp
Labels: hacktoberfest-accepted

#100 Added Z Algorithm for O(N) string search.
  Z_Algorithm.java
Labels: hacktoberfest-accepted

#99 Added Dinic's Algo (Graphs)
  Dinic'sAlgorithm.cpp
Labels: hacktoberfest-accepted

#98 Added Hopcroft-karp-algorithm(Graphs)
  Hopcroft-karp-algorithm.cpp
Labels: hacktoberfest-accepted

#114 Swap_two_Nodes_of_LL.cpp
  LinkedList/Swap_two_Nodes_of_LL.cpp
Labels: hacktoberfest-accepted

#115 Searching element in array.CPP
  Searching_element_inarray.cpp
Labels: hacktoberfest-accepted

#118 Create live_weather.py
  live_weather.py
Labels: hacktoberfest-accepted

#117 Palindrome_LinkedList.cpp
  LinkedList/Palindrome_LinkedList.cpp
Labels: hacktoberfest-accepted

#119 Replace pi (recursive).cpp
  Recursion/Replace pi (recursive).cpp
Labels: hacktoberfest-accepted

#116 kReverse.cpp
  LinkedList/kReverse.cpp
Labels: hacktoberfest-accepted

#120 Reverse_a_Stack.cpp
  Stacks and Queues/Reverse_a_Stack.cpp
Labels: hacktoberfest-accepted

#130 Kahn's algorithm for topological sorting
  Graph/Kahn’s algorithm for Topological Sorting.cpp
Labels: hacktoberfest-accepted

#127 Double Linked List
  LinkedList/DLL.cpp
  LinkedList/tempCodeRunnerFile.cpp
Labels: hacktoberfest-accepted

#126 Inorder tree
  inorder tree.cpp
Labels: hacktoberfest-accepted

#124 Check_redundant_brackets.cpp
  Stacks and Queues/Check_redundant_brackets.cpp
Labels: hacktoberfest-accepted

#123 Reverse_Queue.cpp
  Stacks and Queues/Reverse_Queue.cpp
Labels: hacktoberfest-accepted

#122 Added quicksort
  quick_sort.cpp
Labels: hacktoberfest-accepted

#121 BitMasking
  Bit Masking/Bitwise Manipulation
  Bit Masking/getBit setBit resetBit
Labels: hacktoberfest-accepted

#131 feat : Create nth_node_from_last_node.c
  LinkedList/nth_node_from_last_node.c
Labels: hacktoberfest-accepted

#142 Create InsertionInSortedLinkedList
  InsertioninSortedLinkedList.cpp
  Recursion/CombinationFormula.cpp
Labels: hacktoberfest-accepted

#141 add 2 sum problem of c++
  2sum.cpp
Labels: hacktoberfest-accepted

#138 contributed in Tower of hanoi problem
  Stacks and Queues/Towerofhanoi.c
Labels: hacktoberfest-accepted

#137 Create NumberOfDigitOne.cpp
  Recursion/NumberOfDigitOne.cpp
  Recursion/ReorderList.cpp
  Recursion/SwapNodesInPairs.cpp
Labels: hacktoberfest-accepted

#136 Create detect&removeLOopInLL.cpp
  LinkedList/detect&removeLOopInLL.cpp
Labels: hacktoberfest-accepted

#135 Create subsetOfStringBitwiseWay.cpp
  Bit Masking/subsetOfStringBitwiseWay.cpp
Labels: hacktoberfest-accepted

#133 Create binary_to_decimal_conversion.cpp
  binary_to_decimal_conversion.cpp
Labels: hacktoberfest-accepted

#143 Added Infix to Postfix
  Stacks and Queues/infixtopostfix.cpp
Labels: hacktoberfest-accepted

#147 Contributed in Next Greater Element problem
  Stacks and Queues/NextGreaterElement.cpp
Labels: hacktoberfest-accepted

#146 Sorting Method in Java added
  Sorting/MergeSort.java
Labels: hacktoberfest-accepted

#145 Binary Search added in Java
  Searching/BinarySearch.java
Labels: hacktoberfest-accepted

#144 Added multiplication of polynomials using linkedlist
  LinkedList/polynomial_multiply_linkedlist.cpp
Labels: hacktoberfest-accepted

#149 Dynamic programing using c++
  Dynamic Programming/BinomialCofficient.cpp
  Dynamic Programming/Edit Distance.cpp
  Dynamic Programming/FriendsPairingProblem.cpp
  Dynamic Programming/GoldMineProblem.cpp
  Dynamic Programming/MatixChainMultiplication.cpp
  Dynamic Programming/nthCatalnNumber.cpp
  Dynamic Programming/pairs.cpp
Labels: hacktoberfest-accepted

#148 Arrays DS added in Java
  ArraysDS/ReverseArray.java
Labels: hacktoberfest-accepted

#152 Create Stack.c
  Stacks and Queues/Stack.c
Labels: hacktoberfest-accepted

#150 Create remove linkedlist elements.cpp
  remove linkedlist elements.cpp
Labels: hacktoberfest-accepted

#157 Added code for singly Linkedlist
  Linkedlist.cpp
Labels: hacktoberfest-accepted

#156 Create KthLargestSumSubarray.cpp
  ArraysDS/KthLargestSumSubarray.cpp
Labels: hacktoberfest-accepted

#155 Contributed in Balance Parentheses problem
  Recursion/Insertion_Sort.cpp
  Recursion/factorial.cpp
  Stacks and Queues/balancedparentheses.cpp
Labels: hacktoberfest-accepted

#154 Create Remove_Duplicates_from_Sorted_List.cpp
  LinkedList/Remove_Duplicates_from_Sorted_List.cpp
Labels: hacktoberfest-accepted

#153 Infix to Postfix.c
  Infix_to_Postfix.c
Labels: hacktoberfest-accepted

#160 bubble_sort
  Sorting/bubble_sort.cpp
Labels: hacktoberfest-accepted

#165 feat : Create SparseMatrix.java
  ArraysDS/SparseMatrix.java
Labels: hacktoberfest-accepted

#164 Create FloydDetectionLoop.cpp
  LinkedList/FloydDetectionLoop.cpp
Labels: hacktoberfest-accepted

#163 Create IsPalindrome.cpp
  Recursion/IsPalindrome.cpp
Labels: hacktoberfest-accepted

#162 Create dsa recursion problem word break
  dsa recursion problem word break
Labels: hacktoberfest-accepted

#161 Contributed in quick sort problem
  Recursion/quicksort.cpp
Labels: hacktoberfest-accepted

#169 Added code for reversing stack using recursion
  Stacks and Queues/reverse_stack_using_recursion.cpp
Labels: hacktoberfest-accepted

#168 Create DFS code
  dfs code
Labels: hacktoberfest-accepted

#166 Create Lap timer.py
  Lap timer.py
Labels: hacktoberfest-accepted

#179 Added sorting using stack
  Recursion/factorial_using_recursion.cpp
Labels: hacktoberfest-accepted

#178 Create reverseastringusingrecursion.cpp
  reverseastringusingrecursion.cpp
Labels: hacktoberfest-accepted

#177 Create Longest Substring Without Repeating Characters
  Longest Substring Without Repeating Characters
Labels: hacktoberfest-accepted

#176 sum of digits of a number
  sum_of_digits.cpp
Labels: hacktoberfest-accepted

#175 Create Subarray with given sum
  Subarray with given sum
Labels: hacktoberfest-accepted

#174 added perfectly working recursion code in c++ !!
  Recursion/recursion_working_code.cpp
Labels: hacktoberfest-accepted

#172 Create LinkedListAllfunctions.cpp
  LinkedList/LinkedListAllfunctions.cpp
  Sorting/selection_sort.c
Labels: hacktoberfest-accepted

#171 Splitting the circular linked list
  LinkedList/split_circular_linkedlist.cpp
Labels: hacktoberfest-accepted

#184 Binary Search added
  Binary_Search.cpp
Labels: hacktoberfest-accepted

#183 Create star.java
  star.java
Labels: hacktoberfest-accepted

#182 Create SmallestElement.java
  SmallestElement.java
Labels: hacktoberfest-accepted
